### ISSUE TITLE
Logical values not parsed back correctly.

### ISSUE THREAD

**Issue by jahagirdar** [mkearney/rtweet#52]
I am doing the following in my code

```
  timeline<- get_timeline(pol, n = 4000, max_id = NULL, parse = TRUE,
                            clean_tweets = TRUE,lang="en")
    save_as_csv(timeline,destfile)
```
At a later point I am reading back the saved tweets for processing as follows
```
tweets<-read.csv(paste0("data/",pol,".tweet.tweets.csv"),stringsAsFactors=F)
```
What I have noticed is, This roundtripping converts the Logical column e.g. is_retweet or is_quote_status to string, The odd part is the TRUE string has a space in it i.e. " TRUE" i.e."<space>TRUE" which makes conversion back to logical using as.logical difficult.
for e.g. see attached file

**Comment by mkearney** [comment]
This should be fixed in at least the Github version. The code below worked for me:


```{r}
install.packages("devtools")
devtools::install_github("mkearney/rtweet")
library(rtweet)
timeline <- get_timeline("realDonaldTrump", n = 4000, lang="en")
save_as_csv(timeline, "realDonaldTrump.csv")
rdt <- read.csv("realDonaldTrump.tweets.csv",
                stringsAsFactors = FALSE)
rdt %>%
    lapply(class)
```

**Comment by mkearney** [comment]
short term solution, btw, would be something like this

```{r}
fix.as.logical <- function(x) {
    as.logical(gsub(" ", "", x))
}

timeline$is_retweet <- fix.as.logical(timeline$is_retweet)
## (do that for each logical variable that needs fixing
```

Let me know if that doesn't fix it!

**Comment by jahagirdar** [comment]
I updated to the version on github( version string still shows 0.3.7)
 The problem still exists...

> unique(rdt$is_quote_status)
> [1] "FALSE" " TRUE"

I will go with fix.as.logical for the time being.

**Comment by mkearney** [comment]
Think this is one of the frustrations with write.csv/read.csv. There's probably an easy fix for it, so I'll try to look into it soon.

If you haven't looked into the readr package though now would be a good time 👍

**Comment by jahagirdar** [comment]
While I was aware of readr, I was not aware of any benefit in switching over. I see some atleast in this case.
