### ISSUE TITLE
Error in lookup_users when screen_name only consists of numeric characters

### ISSUE THREAD

**Issue by ashinm** [mkearney/rtweet#82]
There are valid tweeter screen_names that consists of 0-9 alone, e.g. [@108](https://twitter.com/108?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) when I try to pass this in the `lookup_users` function with other screen_names which consists of alphabetical characters as well. Here is a reproducible example

```
users <- c("hadleywickham", "108")
famous_tweeters <- lookup_users(users)
Error in .id_type(x) : users must be user_ids OR screen_names, not both.
```
This is caused by the following block of [code](https://github.com/mkearney/rtweet/blob/master/R/utils.R#L105-L108) which does a test for numeric by applying `as.numeric` on screen_names and if there are coercible to numeric while some are not as in the example outlined above it throws an error assuming the user must have tried to send over a user_id as well as screen_name in the request.

One easy solution would be to force the user to specify the type of query as an additional parameter either user_id or screen_name.

Hope this makes sense, let me know if I'm missing something here.

**Comment by mkearney** [comment]
Thank you for this, @ashinm! I think I realized this problem condition existed a few months ago, but totally forgot about it since then.

The issue should now be fixed. Although your suggestion was totally correct [and what *I* would prefer (as a user) as well], I've opted to keep the user-friendly query logic. So I modified the internal function such that if the vector of user IDs cannot all be converted to numeric, then it's assumed to be a screen name query. I realize this means if you're looking up a single user who happens to have a numeric screen name, this would still fail. So, I'll keep this issue open until I add a little more functionality to deal with that unlikely scenario.

**Comment by ashinm** [comment]
Yeah that logic sounds a lot more robust. Thanks for fixing this so quickly, appreciate it!

**Comment by devarshi11github** [comment]
@ashinm even I faced a similar issue, since one of the username in my database happens to be a number. Can you please elaborate more on the solution, sorry I could not understand. Also there is a limit of 18,000 for looking up users any way to bypass that

**Comment by ashinm** [comment]
@devarshi11github for me the issue was resolved after @mkearney pushed his fix. You would have to break the number of users that you are trying to query into chunks of say 5k and then query them sequentially, at least that's what I did. Use `try` blocks to ascertain if your queries are getting throttled. Hope this helps.

**Comment by devarshi11github** [comment]
@ashinm thanks for your reply. Have you built the code to break the number of users into smaller chunk. It would be great if you can share it. I am still facing the same issue with number as username

**Comment by ashinm** [comment]
A very simple example would look like
```
## Batch into groups of 5k to avoid throttling
twHandles[, group := 1:nrow(missingFavs) %/% 5000 + 1]
userResult = NULL
i = 1
while(i <= max(twHandles$group)) {
	tStart = proc.time()
	message("group: ", i)
	result = try(lookup_users(twHandles[group == i]$tw_handle, tw = FALSE))
	if ("try-error" %in% class(result)) {
		message("rate limit reached sleeping for 5mins")
		Sys.sleep(5 * 60)
	} else {
		userResult = rbindlist(list(userResult, data.table(result)))
		message(paste0("fetched ", nrow(userResult), " rows in ", timetaken(tStart)))
		i = i + 1
	}
}
```
here `twHandle` is my `data.table` of Twitter handles that I want to query.

**Comment by devarshi11github** [comment]
this looks helpful. I just want to check one point (so that I can use the code accurately), I extracted tweets for a brand A and created a dataframe 'Brand A.df'. I stored the usernames in an object 'users' by using a simple command 'users <- unique(BrandA.df$screenName)'

So the 'twHandle' in the above code is 'users'. Is the interpretation correct. Thanks for the help

**Comment by ashinm** [comment]
yeah that sounds right.

**Comment by devarshi11github** [comment]
getting this error in the first line 

"Error in `:=`(group, 1:nrow(missingFavs)%/%5000 + 1) : 
  could not find function ":="

**Comment by ashinm** [comment]
that's `data.table` syntax a basic google search would solve that issue for you.

**Comment by mkearney** [comment]
Update: I've added an `as_screenname()` function, which allows users to coerce values to be treated as screen names rather than user IDs. This is most useful for the `get_friends` or `get_followers` functions:

``` r
## user 1234 followers
flw <- get_followers(as_screenname("1234"))
> flw
# A tibble: 1,370 x 1
              user_id
                <chr>
 1          614705355
 2 881549301599449088
 3 907132553466916865
 4         2516194164
 5         4198996421
 6 897165051962044416
 7          440224080
 8           31473292
 9 895251031956766721
10 787423853379223552
# ... with 1,360 more rows

## list of users
usrs <- list("2973406683", as_screenname("1234"))
fds <- get_friends(usrs)
1 friend networks collected!
2 friend networks collected!
> fds
# A tibble: 626 x 2
         user    user_id
        <chr>      <chr>
 1 2973406683  240051701
 2 2973406683   99840485
 3 2973406683   21238415
 4 2973406683   19685572
 5 2973406683  103657358
 6 2973406683   92435279
 7 2973406683 4902428686
 8 2973406683 1924414555
 9 2973406683 2784033183
10 2973406683 4149978441
# ... with 616 more rows
```
